alert("Bem-vindo a nossa calculadora de idades!")
let NameOldAge = prompt("Insira o Nome da pessoa mais velha: ")
let OldAge = prompt("Insira a idade da pessoa mais velha")
let NameYoungAge = prompt("Insira o nome da pessoa mais nova")
let YoungAge = prompt("Insira a idade da pessoa mais nova")
let DiferenceAge = (OldAge - YoungAge)
alert("Nome da pessoa mais velha: "+ NameOldAge + "\nNome pessoa mais nova: "+ NameYoungAge + "\nDiferença de idade: "+ DiferenceAge +" anos")
